<p>Error on Mar 10, 2016 13:15PM - file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /app/app/Helpers/RainCaptcha.php on line 64</p><p>Error on Mar 10, 2016 13:17PM - file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /app/app/Helpers/RainCaptcha.php on line 64</p><p>Error on Mar 10, 2016 21:22PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 75</p><p>Error on Mar 10, 2016 21:23PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 75</p><p>Error on Mar 10, 2016 21:23PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 75</p><p>Error on Mar 10, 2016 21:23PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 75</p><p>Error on Mar 10, 2016 21:23PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 75</p><p>Error on Mar 10, 2016 21:23PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 75</p><p>Error on Mar 10, 2016 21:25PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:25PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:25PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:26PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:26PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:27PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 21:28PM - Invalid argument supplied for foreach() in /app/app/Modules/Authentifier/Helpers/Feedback.php on line 77</p><p>Error on Mar 10, 2016 22:05PM - Illegal string offset 'message' in /app/app/Modules/Authentifier/Views/Feedback/feedback_message.php on line 2</p><p>Error on Mar 10, 2016 22:05PM - Illegal string offset 'type' in /app/app/Modules/Authentifier/Views/Feedback/feedback_message.php on line 2</p><p>Error on Mar 10, 2016 22:05PM - Illegal string offset 'type' in /app/app/Modules/Authentifier/Views/Feedback/feedback_message.php on line 2</p><p>Error on Mar 10, 2016 22:05PM - Illegal string offset 'type' in /app/app/Modules/Authentifier/Views/Feedback/feedback_message.php on line 2</p><p>Error on Mar 12, 2016 11:41AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 53</p><p>Error on Mar 12, 2016 11:42AM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 53</p><p>Error on Mar 12, 2016 11:43AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 53</p><p>Error on Mar 12, 2016 11:43AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 53</p><p>Error on Mar 12, 2016 11:45AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 54</p><p>Error on Mar 12, 2016 11:46AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 54</p><p>Error on Mar 12, 2016 11:47AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 54</p><p>Error on Mar 12, 2016 11:47AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 54</p><p>Error on Mar 12, 2016 11:48AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 54</p><p>Error on Mar 12, 2016 11:49AM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 55</p><p>Error on Mar 12, 2016 11:50AM - call_user_func() expects parameter 1 to be a valid callback, class 'Modules\Feedback\Helpers\Feedback' does not have a method 'routes' in /app/app/Helpers/Hooks.php on line 162</p><p>Error on Mar 12, 2016 12:06PM - require(/app/app/Modules/Feedback/Views/Feedback/feedback_footer.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 12, 2016 12:13PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 75</p><p>Error on Mar 12, 2016 12:19PM - Cannot use a scalar value as an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 30</p><p>Error on Mar 12, 2016 12:20PM - Cannot use a scalar value as an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 30</p><p>Error on Mar 12, 2016 12:20PM - Invalid argument supplied for foreach() in /app/app/Modules/Feedback/Helpers/Feedback.php on line 56</p><p>Error on Mar 12, 2016 12:20PM - Invalid argument supplied for foreach() in /app/app/Modules/Feedback/Helpers/Feedback.php on line 56</p><p>Error on Mar 12, 2016 12:21PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 72</p><p>Error on Mar 12, 2016 12:22PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 72</p><p>Error on Mar 12, 2016 12:22PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 72</p><p>Error on Mar 12, 2016 12:22PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 72</p><p>Error on Mar 12, 2016 12:28PM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 72</p><p>Error on Mar 12, 2016 12:34PM - array_merge(): Argument #1 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 75</p><p>Error on Mar 12, 2016 12:54PM - array_push() expects parameter 1 to be array, null given in /app/app/Modules/Feedback/Helpers/Feedback.php on line 31</p><p>Error on Mar 12, 2016 12:55PM - array_push() expects parameter 1 to be array, null given in /app/app/Modules/Feedback/Helpers/Feedback.php on line 31</p><p>Error on Mar 12, 2016 13:35PM - session_destroy(): Trying to destroy uninitialized session in /app/app/Helpers/Session.php on line 142</p><p>Error on Mar 12, 2016 20:25PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 40</p><p>Error on Mar 12, 2016 20:30PM - array_merge(): Argument #3 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 26</p><p>Error on Mar 12, 2016 22:32PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 45</p><p>Error on Mar 12, 2016 22:34PM - array_uintersect(): at least 3 parameters are required, 2 given in /app/app/Modules/Feedback/Helpers/Feedback.php on line 48</p><p>Error on Mar 12, 2016 22:42PM - array_uintersect(): at least 3 parameters are required, 2 given in /app/app/Modules/Feedback/Helpers/Feedback.php on line 48</p><p>Error on Mar 12, 2016 22:42PM - array_uintersect(): at least 3 parameters are required, 2 given in /app/app/Modules/Feedback/Helpers/Feedback.php on line 48</p><p>Error on Mar 12, 2016 23:39PM - Constants may only evaluate to scalar values in /app/app/Modules/Authentifier/Controllers/Authentifier.php on line 13</p><p>Error on Mar 12, 2016 23:39PM - Constants may only evaluate to scalar values in /app/app/Modules/Authentifier/Controllers/Authentifier.php on line 13</p><p>Error on Mar 12, 2016 23:39PM - Constants may only evaluate to scalar values in /app/app/Modules/Authentifier/Controllers/Authentifier.php on line 13</p><p>Error on Mar 12, 2016 23:43PM - Constants may only evaluate to scalar values in /app/app/Modules/Feedback/Helpers/Feedback.php on line 21</p><p>Error on Mar 12, 2016 23:49PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 67</p><p>Error on Mar 12, 2016 23:50PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 67</p><p>Error on Mar 12, 2016 23:50PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 67</p><p>Error on Mar 12, 2016 23:50PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 67</p><p>Error on Mar 12, 2016 23:50PM - array_merge(): Argument #2 is not an array in /app/app/Modules/Feedback/Helpers/Feedback.php on line 67</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 1:47AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.userqu' doesn't exist SELECT * FROM userqu WHERE nom</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Modules/Authentifier/Helpers/DB/DBManager.php</p>

           <p><strong>Line:</strong> 59</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Modules/Authentifier/Helpers/DB/Query.php(68): Modules\Authentifier\Helpers\DB\DBManager->execute(Array)
#1 /app/app/Controllers/Welcome.php(57): Modules\Authentifier\Helpers\DB\Query->execute()
#2 /app/app/Controllers/Welcome.php(50): Controllers\Welcome->test()
#3 [internal function]: Controllers\Welcome->index()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 1:58AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.usersqu' doesn't exist SELECT * FROM usersqu ORDER BY id</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Modules/Authentifier/Helpers/DB/DBManager.php</p>

           <p><strong>Line:</strong> 59</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Modules/Authentifier/Helpers/DB/Query.php(68): Modules\Authentifier\Helpers\DB\DBManager->execute(NULL)
#1 /app/app/Controllers/Welcome.php(53): Modules\Authentifier\Helpers\DB\Query->execute()
#2 /app/app/Controllers/Welcome.php(46): Controllers\Welcome->test()
#3 [internal function]: Controllers\Welcome->index()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 1:59AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'order clause' SELECT * FROM users ORDER BY id</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Modules/Authentifier/Helpers/DB/DBManager.php</p>

           <p><strong>Line:</strong> 59</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Modules/Authentifier/Helpers/DB/Query.php(68): Modules\Authentifier\Helpers\DB\DBManager->execute(NULL)
#1 /app/app/Controllers/Welcome.php(52): Modules\Authentifier\Helpers\DB\Query->execute()
#2 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#3 [internal function]: Controllers\Welcome->index()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 13, 2016 2:00AM - PDOStatement::execute() expects parameter 1 to be array, string given in /app/app/Modules/Authentifier/Helpers/DB/DBManager.php on line 57</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 2:01AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'where clause' SELECT * FROM users WHERE Array</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Modules/Authentifier/Helpers/DB/DBManager.php</p>

           <p><strong>Line:</strong> 59</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Modules/Authentifier/Helpers/DB/Query.php(68): Modules\Authentifier\Helpers\DB\DBManager->execute(false)
#1 /app/app/Controllers/Welcome.php(52): Modules\Authentifier\Helpers\DB\Query->execute()
#2 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#3 [internal function]: Controllers\Welcome->index()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 2:28AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause' SELECT * FROM users WHERE Alexandre</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> /app/app/Modules/Authentifier/Helpers/DB/DBManager.php</p>

           <p><strong>Line:</strong> 59</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Modules/Authentifier/Helpers/DB/Query.php(68): Modules\Authentifier\Helpers\DB\DBManager->execute(false)
#1 /app/app/Controllers/Welcome.php(52): Modules\Authentifier\Helpers\DB\Query->execute()
#2 /app/app/Controllers/Welcome.php(45): Controllers\Welcome->test()
#3 [internal function]: Controllers\Welcome->index()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 13, 2016 2:29AM - PDOStatement::execute() expects parameter 1 to be array, string given in /app/app/Modules/Authentifier/Helpers/DB/DBManager.php on line 57</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 2:58AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 2:59AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 2:59AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:00AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: Columns/Parameters are 1-based</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 100</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(100): PDOStatement->bindValue('0', 'Alexandre')
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:00AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:02AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: parameter was not defined</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:04AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:05AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY093]: Invalid parameter number: no parameters were bound</p>

           <p><strong>Code:</strong> HY093</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:05AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:06AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:06AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:06AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 3:06AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Alexandre' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(42): Helpers\Database->select('SELECT * FROM u...', Array)
#2 /app/app/Controllers/Welcome.php(50): Modules\Authentifier\Models\UserModel->findBy('user_name', 'Alexandre')
#3 /app/app/Controllers/Welcome.php(44): Controllers\Welcome->test()
#4 [internal function]: Controllers\Welcome->index()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Controllers\\Wel...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 13, 2016 12:03PM - require(/app/app/Modules//Authentifier/Views/User/user_update.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 13, 2016 12:06PM - require(/app/app/Modules//Authentifier/Views/User/user_update.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 13, 2016 12:07PM - require(/app/app/Modules//Authentifier/Views/Profile/profile_update_form.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 13, 2016 12:07PM - require(/app/app/Modules//Authentifier/Views/Profile/profile_update_form.php): failed to open stream: No such file or directory in /app/app/Core/View.php on line 48</p><p>Error on Mar 13, 2016 15:34PM - call_user_func_array() expects parameter 1 to be a valid callback, class 'Modules\Authentifier\Controllers\Authentifier' does not have a method 'test' in /app/app/Core/Router.php on line 126</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 16:06PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_password' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(73): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Profile.php(61): Modules\Authentifier\Models\UserModel->updateUserProfile(Array, Array)
#3 [internal function]: Modules\Authentifier\Controllers\Profile->profileUpdateAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 13, 2016 16:24PM - ksort() expects parameter 1 to be array, boolean given in /app/app/Helpers/Database.php on line 143</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 16:37PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'alex62d@gmail.com' for key 'user_email'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(73): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Profile.php(69): Modules\Authentifier\Models\UserModel->updateUserProfile(Array, Array)
#3 [internal function]: Modules\Authentifier\Controllers\Profile->profileUpdateAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 13, 2016 19:30PM - password_verify() expects parameter 2 to be string, array given in /app/app/Modules/Authentifier/Controllers/Profile.php on line 62</p><p>Error on Mar 13, 2016 19:31PM - password_verify() expects parameter 2 to be string, array given in /app/app/Modules/Authentifier/Controllers/Profile.php on line 62</p><p>Error on Mar 13, 2016 19:32PM - password_verify() expects parameter 2 to be string, array given in /app/app/Modules/Authentifier/Controllers/Profile.php on line 62</p><p>Error on Mar 13, 2016 19:34PM - Illegal string offset 'user_password_hash' in /app/app/Modules/Authentifier/Controllers/Login.php on line 41</p><p>Error on Mar 13, 2016 19:35PM - Illegal string offset 'user_password_hash' in /app/app/Modules/Authentifier/Controllers/Login.php on line 41</p><p>Error on Mar 13, 2016 19:35PM - Illegal string offset 'user_password_hash' in /app/app/Modules/Authentifier/Controllers/Login.php on line 41</p><p>Error on Mar 13, 2016 19:35PM - Illegal string offset 'user_password_hash' in /app/app/Modules/Authentifier/Controllers/Login.php on line 41</p><p>Error on Mar 13, 2016 19:35PM - Illegal string offset 'user_password_hash' in /app/app/Modules/Authentifier/Controllers/Login.php on line 42</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 19:42PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_new_password' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(74): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Profile.php(74): Modules\Authentifier\Models\UserModel->updateUserProfile(Array, Array)
#3 [internal function]: Modules\Authentifier\Controllers\Profile->profileUpdateAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 13, 2016 19:47PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_password' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 173</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(173): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(74): Helpers\Database->update('users', Array, Array)
#2 /app/app/Modules/Authentifier/Controllers/Profile.php(80): Modules\Authentifier\Models\UserModel->updateUserProfile(Array, Array)
#3 [internal function]: Modules\Authentifier\Controllers\Profile->profileUpdateAction()
#4 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#5 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#6 /app/app/Core/routes.php(29): Core\Router::dispatch()
#7 /app/index.php(81): require('/app/app/Core/r...')
#8 {main}</pre>

           <hr />
<p>Error on Mar 13, 2016 19:53PM - file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /app/app/Helpers/RainCaptcha.php on line 64</p><p>Error on Mar 13, 2016 22:01PM - ksort() expects parameter 1 to be array, null given in /app/app/Helpers/Database.php on line 143</p><p>Error on Mar 13, 2016 22:02PM - ksort() expects parameter 1 to be array, null given in /app/app/Helpers/Database.php on line 143</p>