<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 16, 2016 23:32PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(64): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(54): Modules\Authentifier\Models\UserModel->selectID('jerome')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(46): Modules\Authentifier\Controllers\Login->loginActionDatabase('jerome', 'harley')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Mar 17, 2016 21:05PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authentifier.users' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> /app/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 104</p>

           <h3>Stack trace:</h3>

           <pre>#0 /app/app/Helpers/Database.php(104): PDOStatement->execute()
#1 /app/app/Modules/Authentifier/Models/UserModel.php(64): Helpers\Database->select('SELECT user_id ...', Array, 2)
#2 /app/app/Modules/Authentifier/Controllers/Login.php(54): Modules\Authentifier\Models\UserModel->selectID('admin')
#3 /app/app/Modules/Authentifier/Controllers/Login.php(46): Modules\Authentifier\Controllers\Login->loginActionDatabase('admin', '********')
#4 [internal function]: Modules\Authentifier\Controllers\Login->loginAction()
#5 /app/app/Core/Router.php(126): call_user_func_array(Array, Array)
#6 /app/app/Core/Router.php(217): Core\Router::invokeObject('Modules\\Authent...')
#7 /app/app/Core/routes.php(29): Core\Router::dispatch()
#8 /app/index.php(81): require('/app/app/Core/r...')
#9 {main}</pre>

           <hr />
<p>Error on Mar 17, 2016 21:17PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:17PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:18PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:18PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:18PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p><p>Error on Mar 17, 2016 21:19PM - Invalid argument supplied for foreach() in /app/app/Helpers/Database.php on line 96</p>